import type { UniverseName } from "./universe";

function eq(
  symbol: string,
  name: string,
  sector: string,
  themes: string[],
  quality: number,
  thesis: string,
): UniverseName {
  return {
    symbol,
    name,
    last: 0,
    sma20: 0,
    sma50: 0,
    high20: 0,
    low20: 0,
    rsi: 50,
    atrPct: 0.018,
    quality,
    ownership: Math.max(4, quality - 0.8),
    sentiment: 6.2,
    themes,
    thesis,
    sector,
    assetClass: "equity",
    quote: "INR",
    venue: "NSE",
  };
}

function x(
  symbol: string,
  name: string,
  assetClass: UniverseName["assetClass"],
  quote: UniverseName["quote"],
  venue: string,
  themes: string[],
  thesis: string,
  sector: string,
): UniverseName {
  return {
    symbol,
    name,
    last: 0,
    sma20: 0,
    sma50: 0,
    high20: 0,
    low20: 0,
    rsi: 50,
    atrPct: assetClass === "crypto" ? 0.035 : 0.008,
    quality: 6.5,
    ownership: 6,
    sentiment: 6.2,
    themes,
    thesis,
    sector,
    assetClass,
    quote,
    venue,
  };
}

/** Extra NSE / crypto / FX names beyond the core researched book. */
export const EXTRA_NAMES: UniverseName[] = [
  eq("AXISBANK", "Axis Bank", "Banks", ["banks"], 7.4, "Private bank. Rates and credit costs set the tape."),
  eq("KOTAKBANK", "Kotak Mahindra Bank", "Banks", ["banks"], 7.6, "Premium private bank. Valuation is the gate."),
  eq("BAJFINANCE", "Bajaj Finance", "NBFC", ["nbfc", "credit"], 7.2, "Retail credit beta. Stress regime cuts size."),
  eq("BAJAJFINSV", "Bajaj Finserv", "Financials", ["nbfc"], 7.0, "Holdco over lending and insurance."),
  eq("HDFCLIFE", "HDFC Life", "Insurance", ["insurance"], 7.1, "Life franchise. Rate-sensitive multiple."),
  eq("SBILIFE", "SBI Life", "Insurance", ["insurance"], 7.3, "Agency machine. Quality over chase."),
  eq("MARUTI", "Maruti Suzuki", "Auto", ["auto"], 7.5, "Domestic PV leader. Rural + GST tape."),
  eq("M&M", "Mahindra & Mahindra", "Auto", ["auto", "farm"], 7.8, "UV + farm + EV optionality."),
  eq("TATAMOTORS", "Tata Motors", "Auto", ["auto", "ev"], 6.8, "JLR cash vs India EV spend."),
  eq("EICHERMOT", "Eicher Motors", "Auto", ["auto"], 7.4, "Royal Enfield premium mix."),
  eq("HEROMOTOCO", "Hero MotoCorp", "Auto", ["auto"], 6.6, "Two-wheeler volume. Rural monsoon."),
  eq("TATASTEEL", "Tata Steel", "Metals", ["metals", "steel"], 6.4, "Europe + India steel. China prints matter."),
  eq("JSWSTEEL", "JSW Steel", "Metals", ["metals", "steel"], 6.5, "Domestic steel. Spread over volume."),
  eq("HINDALCO", "Hindalco", "Metals", ["metals", "aluminium"], 6.7, "Aluminium + Novelis. US industrial."),
  eq("VEDL", "Vedanta", "Metals", ["metals", "commodity"], 5.8, "Diversified metals. Balance-sheet first."),
  eq("SUNPHARMA", "Sun Pharma", "Pharma", ["pharma"], 7.9, "Specialty + India brands."),
  eq("CIPLA", "Cipla", "Pharma", ["pharma"], 7.5, "US generics + India respiratory."),
  eq("DRREDDY", "Dr Reddy's", "Pharma", ["pharma"], 7.2, "US pipeline vs price erosion."),
  eq("APOLLOHOSP", "Apollo Hospitals", "Healthcare", ["health"], 7.6, "Hospital + diagnostics compounder."),
  eq("MAXHEALTH", "Max Healthcare", "Healthcare", ["health"], 7.3, "Metro hospital density."),
  eq("TITAN", "Titan", "Consumer", ["jewellery", "retail"], 7.7, "Jewellery + watches. Gold price is a mix, not the P&L."),
  eq("ASIANPAINT", "Asian Paints", "Consumer", ["paints"], 7.4, "Decorative leader. Volume over price."),
  eq("NESTLEIND", "Nestlé India", "FMCG", ["fmcg"], 8.0, "Quality compounder. Valuation is the gate."),
  eq("BRITANNIA", "Britannia", "FMCG", ["fmcg"], 7.6, "Foods. Rural recovery."),
  eq("TATACONSUM", "Tata Consumer", "FMCG", ["fmcg"], 7.1, "Tea + staples + distribution."),
  eq("ULTRACEMCO", "UltraTech Cement", "Cement", ["cement", "infra"], 7.4, "Street-plus cement. Infra cycle."),
  eq("GRASIM", "Grasim", "Cement", ["cement", "chemicals"], 6.9, "Cement holdco + viscose."),
  eq("COALINDIA", "Coal India", "Energy", ["energy", "psu"], 6.8, "Volume + dividend. Policy risk."),
  eq("ONGC", "ONGC", "Energy", ["energy", "oil"], 6.5, "Upstream. Crude beta."),
  eq("BPCL", "BPCL", "Energy", ["energy", "oil"], 6.3, "OMCs. Marketing margin over crude."),
  eq("ADANIENT", "Adani Enterprises", "Infra", ["infra", "energy"], 6.2, "Incubator. High beta, size small."),
  eq("ADANIPORTS", "Adani Ports", "Infra", ["infra", "ports"], 6.8, "Ports + logistics volume."),
  eq("BEL", "Bharat Electronics", "Defence", ["defence"], 7.5, "Defence electronics order book."),
  eq("HCLTECH", "HCL Technologies", "IT", ["it-services"], 8.0, "IT services. Deal cycle over multiple."),
  eq("WIPRO", "Wipro", "IT", ["it-services"], 7.2, "Turnaround IT. Wait for organic."),
  eq("TECHM", "Tech Mahindra", "IT", ["it-services"], 6.9, "Communications vertical."),
  eq("PERSISTENT", "Persistent Systems", "IT", ["it-services", "ai"], 7.4, "Mid-tier AI services."),
  eq("COFORGE", "Coforge", "IT", ["it-services"], 7.1, "Travel + BFS mid-tier."),
  eq("LTTS", "L&T Technology", "IT", ["it-services", "engineering"], 7.3, "ER&D. Auto + medical."),
  eq("TATATECH", "Tata Technologies", "IT", ["engineering", "auto"], 6.8, "Auto ER&D. Execution first."),
  eq("INDUSINDBK", "IndusInd Bank", "Banks", ["banks"], 5.9, "Repair story. Size tiny until asset quality prints clean."),
  eq("TRENT", "Trent", "Retail", ["retail"], 7.6, "Westside + Zudio compounding."),
  eq("JIOFIN", "Jio Financial", "NBFC", ["nbfc"], 6.4, "New finance stack. Wait for ROE, not the name."),
  eq("SHRIRAMFIN", "Shriram Finance", "NBFC", ["nbfc"], 6.7, "CV + MSME credit."),
  eq("DLF", "DLF", "Realty", ["realty"], 6.5, "Office + luxury residential."),
  eq("IRFC", "IRFC", "PSU", ["psu", "rail"], 6.2, "Railway finco. Yield name."),
  eq("PFC", "Power Finance", "PSU", ["psu", "power"], 6.6, "Power financier. Spreads + asset quality."),
  eq("RECLTD", "REC", "PSU", ["psu", "power"], 6.6, "Power financier twin."),
  eq("SUZLON", "Suzlon", "Renewables", ["power", "renewable"], 5.8, "Wind OEM. Balance sheet first."),
  eq("WAAREEENER", "Waaree Energies", "Renewables", ["power", "solar", "ai-data-center"], 6.5, "Solar OEM. Data-center power is a theme, not a fill."),
  eq("VOLTAS", "Voltas", "Consumer disc.", ["cooling", "ems"], 6.8, "AC + projects. Summer tape."),
  eq("BLUESTARCO", "Blue Star", "Consumer disc.", ["cooling"], 7.0, "Commercial cooling."),
  eq("CUMMINSIND", "Cummins India", "Capital goods", ["power", "ai-data-center"], 7.7, "Gensets for campuses and data halls."),
  eq("APLAPOLLO", "APL Apollo", "Steel", ["steel", "infra"], 7.2, "Structural tubes. Construction cycle."),
  eq("ASTRAL", "Astral", "Pipes", ["pipes", "infra"], 7.1, "Pipes + adhesives."),
  eq("PIDILITIND", "Pidilite", "Chemicals", ["chemicals"], 8.1, "Fevicol franchise. Quality hold."),
  eq("MCX", "MCX", "Exchanges", ["markets"], 7.0, "Commodity exchange. Volume + gold tape."),
  eq("BSE", "BSE", "Exchanges", ["markets"], 6.8, "Cash + derivatives mix."),
  eq("CDSL", "CDSL", "Exchanges", ["markets"], 7.2, "Depository. Account adds."),
  x("BNB", "BNB", "crypto", "USD", "Delta", ["crypto"], "Exchange token beta. Size small.", "Crypto"),
  x("ADA", "Cardano", "crypto", "USD", "Delta", ["crypto"], "L1 beta. Weekend gaps.", "Crypto"),
  x("DOGE", "Dogecoin", "crypto", "USD", "Delta", ["crypto"], "Meme beta. Skip unless heat is empty.", "Crypto"),
  x("LINK", "Chainlink", "crypto", "USD", "Delta", ["crypto"], "Oracle beta. Follows ETH.", "Crypto"),
  x("AUDUSD", "AUD / USD", "forex", "FX", "Spot FX", ["forex", "dollar"], "China-proxy dollar pair.", "FX"),
  x("EURINR", "EUR / INR", "forex", "FX", "Spot FX", ["forex", "rupee"], "Euro rupee. Cross of EURUSD × USDINR.", "FX"),
  x("ZINC", "Zinc", "commodity", "INR", "MCX", ["commodity", "metals"], "Industrial metal. China prints.", "Base metal"),
];
