import type { UniverseName } from "./universe";

function row(
  symbol: string,
  name: string,
  assetClass: NonNullable<UniverseName["assetClass"]>,
  quote: NonNullable<UniverseName["quote"]>,
  venue: string,
  sector: string,
  themes: string[],
  thesis: string,
  quality = 6.5,
): UniverseName {
  return {
    symbol,
    name,
    last: 0,
    sma20: 0,
    sma50: 0,
    high20: 0,
    low20: 0,
    rsi: 50,
    atrPct: assetClass === "crypto" ? 0.04 : assetClass === "options" ? 0.08 : 0.016,
    quality,
    ownership: 6,
    sentiment: 6.2,
    themes,
    thesis,
    sector,
    assetClass,
    quote,
    venue,
  };
}

function eq(symbol: string, name: string, sector: string, themes: string[], quality: number, thesis: string) {
  return row(symbol, name, "equity", "INR", "NSE", sector, themes, thesis, quality);
}

export const SLEEVE_NAMES: UniverseName[] = [
  eq("SENSEX", "S&P BSE Sensex", "Index", ["index"], 8, "Benchmark. Use as overlay, not a clip."),
  eq("FINNIFTY", "Nifty Financial Services", "Index", ["index", "banks"], 7.4, "Financials index. Bank + NBFC beta."),
  eq("BAJAJ-AUTO", "Bajaj Auto", "Auto", ["auto"], 7.4, "Two-wheeler + export mix."),
  eq("DIVISLAB", "Divi's Labs", "Pharma", ["pharma"], 7.6, "API quality. USFDA is the gate."),
  eq("HAL", "Hindustan Aeronautics", "Defence", ["defence"], 7.5, "Defence OEM order book."),
  eq("TVSMOTOR", "TVS Motor", "Auto", ["auto"], 7.3, "Two-wheeler mix upgrade."),
  eq("ASHOKLEY", "Ashok Leyland", "Auto", ["auto", "cv"], 6.6, "CV cycle."),
  eq("MOTHERSON", "Samvardhana Motherson", "Auto anc.", ["auto"], 6.8, "Global auto ancillary."),
  eq("IRCTC", "IRCTC", "Rail", ["rail", "consumer"], 6.9, "Rail catering + tickets. Multiple is the gate."),
  eq("GAIL", "GAIL", "Energy", ["energy", "gas"], 6.7, "Gas transmission + petchem."),
  eq("IOC", "Indian Oil", "Energy", ["energy", "oil"], 6.4, "OMC. Marketing margin."),
  eq("HINDPETRO", "HPCL", "Energy", ["energy", "oil"], 6.3, "OMC twin."),
  eq("PETRONET", "Petronet LNG", "Energy", ["energy", "gas"], 6.8, "LNG throughput."),
  eq("ADANIGREEN", "Adani Green", "Renewables", ["power", "renewable"], 6.2, "RE capacity. Size small."),
  eq("ADANIPOWER", "Adani Power", "Power", ["power"], 6.1, "Thermal. Policy + leverage."),
  eq("TATACOMM", "Tata Communications", "Telecom", ["telecom", "ai-data-center"], 7.2, "Data + network for campuses."),
  eq("INDUSTOWER", "Indus Towers", "Telecom", ["telecom"], 6.7, "Tower tenancy."),
  eq("BANKBARODA", "Bank of Baroda", "Banks", ["banks", "psu"], 6.6, "PSU bank. Credit costs."),
  eq("PNB", "Punjab National Bank", "Banks", ["banks", "psu"], 6.3, "PSU bank."),
  eq("CANBK", "Canara Bank", "Banks", ["banks", "psu"], 6.4, "PSU bank."),
  eq("FEDERALBNK", "Federal Bank", "Banks", ["banks"], 7.0, "South private bank."),
  eq("IDFCFIRSTB", "IDFC First Bank", "Banks", ["banks"], 6.5, "Retail build-out."),
  eq("AUBANK", "AU Small Finance", "Banks", ["banks"], 6.6, "SFB. Asset quality first."),
  eq("CHOLAFIN", "Cholamandalam", "NBFC", ["nbfc"], 7.1, "Vehicle finance."),
  eq("MUTHOOTFIN", "Muthoot Finance", "NBFC", ["nbfc"], 6.9, "Gold loan."),
  eq("LICI", "LIC", "Insurance", ["insurance"], 6.8, "Life giant. Float + equity."),
  eq("DMART", "Avenue Supermarts", "Retail", ["retail"], 7.4, "Value retail. Valuation gate."),
  eq("ZOMATO", "Eternal (Zomato)", "Consumer int.", ["internet"], 6.7, "Food + quick commerce."),
  eq("NAUKRI", "Info Edge", "Internet", ["internet"], 7.2, "Jobs + 99acres + Zomato stake."),
  eq("PAYTM", "Paytm", "Fintech", ["fintech"], 5.8, "Repair story. Size tiny."),
  eq("PIIND", "PI Industries", "Agri chem", ["chemicals"], 7.3, "CSM + agchem."),
  eq("SRF", "SRF", "Chemicals", ["chemicals"], 7.1, "Fluorochemicals + packaging."),
  eq("DEEPAKNTR", "Deepak Nitrite", "Chemicals", ["chemicals"], 6.8, "Phenolics cycle."),
  eq("UPL", "UPL", "Agri chem", ["chemicals"], 5.9, "Crop protection. Leverage first."),
  eq("PAGEIND", "Page Industries", "Consumer", ["apparel"], 7.5, "Jockey India. Quality hold."),
  eq("DABUR", "Dabur", "FMCG", ["fmcg"], 7.2, "Ayurveda staples."),
  eq("MARICO", "Marico", "FMCG", ["fmcg"], 7.3, "Hair oil + foods."),
  eq("COLPAL", "Colgate-Palmolive", "FMCG", ["fmcg"], 7.6, "Oral care."),
  eq("BERGEPAINT", "Berger Paints", "Paints", ["paints"], 7.0, "No.2 decorative."),
  eq("SHREECEM", "Shree Cement", "Cement", ["cement"], 7.4, "Efficiency leader."),
  eq("AMBUJACEM", "Ambuja Cements", "Cement", ["cement"], 6.9, "Adani cement."),
  eq("JINDALSTEL", "Jindal Steel", "Metals", ["steel"], 6.6, "Domestic steel."),
  eq("NMDC", "NMDC", "Metals", ["metals", "iron"], 6.5, "Iron ore. China prints."),
  eq("HINDZINC", "Hindustan Zinc", "Metals", ["metals", "zinc"], 6.7, "Zinc + silver byproduct."),
  eq("NATIONALUM", "NALCO", "Metals", ["aluminium"], 6.3, "Aluminium PSU."),
  eq("SAIL", "SAIL", "Metals", ["steel", "psu"], 6.0, "PSU steel."),

  row("AVAX", "Avalanche", "crypto", "USD", "Binance", "Crypto", ["crypto"], "L1 beta. Binance USDT."),
  row("DOT", "Polkadot", "crypto", "USD", "Binance", "Crypto", ["crypto"], "Relay-chain beta."),
  row("SUI", "Sui", "crypto", "USD", "Binance", "Crypto", ["crypto"], "High-beta L1."),
  row("NEAR", "NEAR", "crypto", "USD", "Binance", "Crypto", ["crypto"], "L1 beta."),
  row("APT", "Aptos", "crypto", "USD", "Binance", "Crypto", ["crypto"], "Move L1."),
  row("ARB", "Arbitrum", "crypto", "USD", "Binance", "Crypto", ["crypto"], "ETH L2."),
  row("OP", "Optimism", "crypto", "USD", "Binance", "Crypto", ["crypto"], "ETH L2."),
  row("LTC", "Litecoin", "crypto", "USD", "Binance", "Crypto", ["crypto"], "Old-beta BTC cousin."),
  row("BCH", "Bitcoin Cash", "crypto", "USD", "Binance", "Crypto", ["crypto"], "Fork beta."),
  row("TRX", "TRON", "crypto", "USD", "Binance", "Crypto", ["crypto"], "Stablecoin rail."),
  row("FIL", "Filecoin", "crypto", "USD", "Binance", "Crypto", ["crypto"], "Storage beta."),
  row("ATOM", "Cosmos", "crypto", "USD", "Binance", "Crypto", ["crypto"], "IBC beta."),
  row("UNI", "Uniswap", "crypto", "USD", "Binance", "Crypto", ["crypto"], "DEX fee beta."),
  row("AAVE", "Aave", "crypto", "USD", "Binance", "Crypto", ["crypto"], "Lending beta."),
  row("INJ", "Injective", "crypto", "USD", "Binance", "Crypto", ["crypto"], "On-chain derivatives."),
  row("TIA", "Celestia", "crypto", "USD", "Binance", "Crypto", ["crypto"], "DA layer."),
  row("FET", "Artificial Superintelligence", "crypto", "USD", "Binance", "Crypto", ["crypto", "ai"], "AI-agent token. High beta."),
  row("RENDER", "Render", "crypto", "USD", "Binance", "Crypto", ["crypto", "ai"], "GPU render network."),
  row("TAO", "Bittensor", "crypto", "USD", "Binance", "Crypto", ["crypto", "ai"], "AI subnet beta."),
  row("HBAR", "Hedera", "crypto", "USD", "Binance", "Crypto", ["crypto"], "Hashgraph."),
  row("XLM", "Stellar", "crypto", "USD", "Binance", "Crypto", ["crypto"], "Payments rail."),
  row("ETC", "Ethereum Classic", "crypto", "USD", "Binance", "Crypto", ["crypto"], "ETH cousin."),
  row("ICP", "Internet Computer", "crypto", "USD", "Binance", "Crypto", ["crypto"], "On-chain compute."),
  row("ONDO", "Ondo", "crypto", "USD", "Binance", "Crypto", ["crypto"], "RWA beta."),
  row("WLD", "Worldcoin", "crypto", "USD", "Binance", "Crypto", ["crypto"], "ID + token. Size tiny."),
  row("PEPE", "Pepe", "crypto", "USD", "Binance", "Crypto", ["crypto"], "Meme. Skip unless heat is empty."),
  row("SHIB", "Shiba Inu", "crypto", "USD", "Binance", "Crypto", ["crypto"], "Meme. Size tiny."),
  row("TON", "Toncoin", "crypto", "USD", "Binance", "Crypto", ["crypto"], "Telegram-rail L1."),
  row("SEI", "Sei", "crypto", "USD", "Binance", "Crypto", ["crypto"], "Trading L1."),
  row("RUNE", "THORChain", "crypto", "USD", "Binance", "Crypto", ["crypto"], "Cross-chain liquidity."),
  row("MKR", "Maker", "crypto", "USD", "Binance", "Crypto", ["crypto"], "DAI governance."),
  row("ENA", "Ethena", "crypto", "USD", "Binance", "Crypto", ["crypto"], "Synthetic dollar. High beta."),
  row("PAXG", "PAX Gold", "crypto", "USD", "Binance", "Crypto", ["crypto", "gold"], "Tokenised gold. Follows COMEX."),

  row("NZDUSD", "NZD / USD", "forex", "FX", "Spot FX", "FX", ["forex", "dollar"], "Kiwi. China + dairy."),
  row("USDCAD", "USD / CAD", "forex", "FX", "Spot FX", "FX", ["forex", "dollar"], "Oil-linked dollar pair."),
  row("USDCHF", "USD / CHF", "forex", "FX", "Spot FX", "FX", ["forex", "dollar"], "Safe-haven franc."),
  row("EURJPY", "EUR / JPY", "forex", "FX", "Spot FX", "FX", ["forex"], "Risk-on cross."),
  row("GBPJPY", "GBP / JPY", "forex", "FX", "Spot FX", "FX", ["forex"], "Whippy cross. Size down."),
  row("EURGBP", "EUR / GBP", "forex", "FX", "Spot FX", "FX", ["forex"], "Europe vs sterling."),
  row("GBPINR", "GBP / INR", "forex", "FX", "Spot FX", "FX", ["forex", "rupee"], "Sterling rupee."),
  row("JPYINR", "JPY / INR", "forex", "FX", "Spot FX", "FX", ["forex", "rupee"], "Yen rupee."),
  row("USDCNH", "USD / CNH", "forex", "FX", "Spot FX", "FX", ["forex", "dollar"], "Offshore yuan."),

  row("BRENT", "Brent (MCX est.)", "commodity", "INR", "MCX", "Energy", ["commodity", "crude"], "Brent × USDINR."),
  row("PLATINUM", "Platinum (MCX est.)", "commodity", "INR", "MCX", "Bullion", ["commodity", "platinum"], "COMEX × USDINR, 10g."),
  row("PALLADIUM", "Palladium", "commodity", "INR", "MCX", "Bullion", ["commodity"], "Auto-cat metal."),
  row("WHEAT", "Wheat", "commodity", "USD", "CBOT", "Agri", ["commodity", "agri"], "CBOT wheat. Food inflation tape."),
  row("CORN", "Corn", "commodity", "USD", "CBOT", "Agri", ["commodity", "agri"], "CBOT corn."),
  row("SOY", "Soybeans", "commodity", "USD", "CBOT", "Agri", ["commodity", "agri"], "CBOT soy."),
  row("COTTON", "Cotton", "commodity", "USD", "ICE", "Agri", ["commodity", "agri"], "ICE cotton. India export mix."),
  row("COFFEE", "Coffee", "commodity", "USD", "ICE", "Agri", ["commodity", "agri"], "ICE arabica."),
  row("COCOA", "Cocoa", "commodity", "USD", "ICE", "Agri", ["commodity", "agri"], "ICE cocoa. Whippy."),

  row("NIFTYFUT", "Nifty futures", "futures", "INR", "NFO", "Index fut", ["futures", "index"], "Near-month Nifty. Paper overlay."),
  row("BANKNIFTYFUT", "Bank Nifty futures", "futures", "INR", "NFO", "Index fut", ["futures", "banks"], "Near-month Bank Nifty."),
  row("FINNIFTYFUT", "FinNifty futures", "futures", "INR", "NFO", "Index fut", ["futures"], "Financials future."),
  row("SENSEXFUT", "Sensex futures", "futures", "INR", "BFO", "Index fut", ["futures"], "BSE Sensex future."),
  row("RELIANCEFUT", "Reliance futures", "futures", "INR", "NFO", "Stock fut", ["futures"], "Stock future on RELIANCE."),
  row("HDFCBANKFUT", "HDFC Bank futures", "futures", "INR", "NFO", "Stock fut", ["futures", "banks"], "Stock future on HDFCBANK."),
  row("TCSFUT", "TCS futures", "futures", "INR", "NFO", "Stock fut", ["futures"], "Stock future on TCS."),
  row("GOLDFUT", "Gold futures", "futures", "INR", "MCX", "Bullion fut", ["futures", "gold"], "MCX gold future."),
  row("CRUDEFUT", "Crude futures", "futures", "INR", "MCX", "Energy fut", ["futures", "crude"], "MCX crude future."),
  row("BTCPERP", "BTC-USDT perp", "futures", "USD", "Binance", "Crypto perp", ["futures", "crypto"], "Binance USDT-M perpetual. Paper, live last."),
  row("ETHPERP", "ETH-USDT perp", "futures", "USD", "Binance", "Crypto perp", ["futures", "crypto"], "ETH USDT-M perpetual. Paper, live last."),
  row("SOLPERP", "SOL-USDT perp", "futures", "USD", "Binance", "Crypto perp", ["futures", "crypto"], "SOL USDT-M perpetual. Paper, live last."),
  row("BTCUSDPERP", "BTCUSD coin-m perp", "futures", "USD", "Binance", "Crypto perp", ["futures", "crypto"], "Binance COIN-M BTC perpetual."),
  row("ETHUSDPERP", "ETHUSD coin-m perp", "futures", "USD", "Binance", "Crypto perp", ["futures", "crypto"], "Binance COIN-M ETH perpetual."),

  row("NIFTYCE", "Nifty ATM call", "options", "INR", "NFO", "Index opt", ["options"], "Weekly ATM call with expiry and strike on the tape. Model premium unless a live print exists."),
  row("NIFTYPE", "Nifty ATM put", "options", "INR", "NFO", "Index opt", ["options"], "Weekly ATM put. Hedge sleeve."),
  row("BANKNIFTYCE", "Bank Nifty ATM call", "options", "INR", "NFO", "Index opt", ["options"], "Weekly ATM call."),
  row("BANKNIFTYPE", "Bank Nifty ATM put", "options", "INR", "NFO", "Index opt", ["options"], "Weekly ATM put."),
  row("RELIANCECE", "Reliance ATM call", "options", "INR", "NFO", "Stock opt", ["options"], "Stock ATM call. Model premium."),
  row("RELIANCEPE", "Reliance ATM put", "options", "INR", "NFO", "Stock opt", ["options"], "Stock ATM put."),
  row("HDFCBANKCE", "HDFC Bank ATM call", "options", "INR", "NFO", "Stock opt", ["options"], "Stock ATM call."),
  row("HDFCBANKPE", "HDFC Bank ATM put", "options", "INR", "NFO", "Stock opt", ["options"], "Stock ATM put."),
  row("BTCCM", "BTC ATM call", "options", "USD", "Delta", "Crypto opt", ["options", "crypto"], "BTC ATM call. Live Binance option when listed, else model with expiry and strike."),
  row("BTCPE", "BTC ATM put", "options", "USD", "Delta", "Crypto opt", ["options", "crypto"], "BTC ATM put. Live Binance option when listed, else model with expiry and strike."),
];
