import type { Factor, Regime } from "./scoring";
import { EXTRA_NAMES } from "./names-extra";
import { SLEEVE_NAMES } from "./names-sleeves";
import { SNAPSHOT } from "./tickers";

export type AssetClass = "equity" | "crypto" | "forex" | "commodity" | "futures" | "options";

export type UniverseName = {
  symbol: string;
  name: string;
  last: number;
  sma20: number;
  sma50: number;
  high20: number;
  low20: number;
  rsi: number;
  atrPct: number;
  quality: number;
  ownership: number;
  sentiment: number;
  themes: string[];
  thesis: string;
  sector: string;
  assetClass?: AssetClass;
  quote?: "INR" | "USD" | "FX";
  venue?: string;
};

const CORE_UNIVERSE: UniverseName[] = [
  {
    symbol: "RELIANCE",
    name: "Reliance Industries",
    last: 1398,
    sma20: 1382,
    sma50: 1364,
    high20: 1442,
    low20: 1328,
    rsi: 57,
    atrPct: 0.016,
    quality: 8.2,
    ownership: 7.4,
    sentiment: 6.8,
    themes: ["energy", "infra", "ai-data-center"],
    thesis: "Jio/data-center power + petrochem cash engine.",
    sector: "Energy",
  },
  {
    symbol: "TCS",
    name: "Tata Consultancy Services",
    last: 3124,
    sma20: 3160,
    sma50: 3210,
    high20: 3288,
    low20: 3040,
    rsi: 42,
    atrPct: 0.014,
    quality: 9.1,
    ownership: 8.6,
    sentiment: 5.4,
    themes: ["it-services"],
    thesis: "Quality compounder; near-term demand still mixed.",
    sector: "IT",
  },
  {
    symbol: "INFY",
    name: "Infosys",
    last: 1488,
    sma20: 1512,
    sma50: 1540,
    high20: 1586,
    low20: 1442,
    rsi: 38,
    atrPct: 0.017,
    quality: 8.6,
    ownership: 8.2,
    sentiment: 5.1,
    themes: ["it-services"],
    thesis: "Large-cap IT; waiting for deal-win inflection.",
    sector: "IT",
  },
  {
    symbol: "HDFCBANK",
    name: "HDFC Bank",
    last: 1672,
    sma20: 1654,
    sma50: 1638,
    high20: 1710,
    low20: 1598,
    rsi: 58,
    atrPct: 0.013,
    quality: 8.8,
    ownership: 8.4,
    sentiment: 6.6,
    themes: ["banks"],
    thesis: "Core compounding bank; margin of safety improving.",
    sector: "Banks",
  },
  {
    symbol: "ICICIBANK",
    name: "ICICI Bank",
    last: 1224,
    sma20: 1210,
    sma50: 1194,
    high20: 1268,
    low20: 1162,
    rsi: 61,
    atrPct: 0.015,
    quality: 8.4,
    ownership: 8.0,
    sentiment: 7.1,
    themes: ["banks"],
    thesis: "Retail franchise still taking share.",
    sector: "Banks",
  },
  {
    symbol: "SBIN",
    name: "State Bank of India",
    last: 812,
    sma20: 798,
    sma50: 784,
    high20: 846,
    low20: 756,
    rsi: 63,
    atrPct: 0.018,
    quality: 7.2,
    ownership: 6.8,
    sentiment: 6.9,
    themes: ["banks"],
    thesis: "Credit cycle + deposit franchise; cyclical beta.",
    sector: "Banks",
  },
  {
    symbol: "BHARTIARTL",
    name: "Bharti Airtel",
    last: 1886,
    sma20: 1864,
    sma50: 1810,
    high20: 1944,
    low20: 1768,
    rsi: 64,
    atrPct: 0.016,
    quality: 8.0,
    ownership: 7.6,
    sentiment: 7.4,
    themes: ["infra", "ai-data-center"],
    thesis: "ARPU upcycle; towers and data traffic as AI compute lands.",
    sector: "Telecom",
  },
  {
    symbol: "ITC",
    name: "ITC",
    last: 492,
    sma20: 498,
    sma50: 506,
    high20: 518,
    low20: 478,
    rsi: 41,
    atrPct: 0.012,
    quality: 8.3,
    ownership: 7.8,
    sentiment: 4.8,
    themes: ["fmcg"],
    thesis: "Cash-rich FMCG; cigarette mix still the engine.",
    sector: "FMCG",
  },
  {
    symbol: "LT",
    name: "Larsen & Toubro",
    last: 3620,
    sma20: 3588,
    sma50: 3510,
    high20: 3724,
    low20: 3410,
    rsi: 59,
    atrPct: 0.017,
    quality: 8.1,
    ownership: 7.5,
    sentiment: 7.2,
    themes: ["infra", "ai-data-center", "power"],
    thesis: "Order book + data-center / power EPC optionality.",
    sector: "Infra",
  },
  {
    symbol: "HINDUNILVR",
    name: "Hindustan Unilever",
    last: 2648,
    sma20: 2662,
    sma50: 2688,
    high20: 2740,
    low20: 2588,
    rsi: 46,
    atrPct: 0.011,
    quality: 9.0,
    ownership: 8.7,
    sentiment: 5.2,
    themes: ["fmcg"],
    thesis: "Quality staple; volume recovery still uneven.",
    sector: "FMCG",
  },
  {
    symbol: "POLYCAB",
    name: "Polycab India",
    last: 6684,
    sma20: 6520,
    sma50: 6288,
    high20: 6890,
    low20: 6040,
    rsi: 66,
    atrPct: 0.024,
    quality: 7.8,
    ownership: 6.9,
    sentiment: 7.8,
    themes: ["cables", "ai-data-center", "power"],
    thesis: "Wires, cables, and FMEG for data-center and housing power.",
    sector: "Cables",
  },
  {
    symbol: "KEI",
    name: "KEI Industries",
    last: 4128,
    sma20: 3984,
    sma50: 3810,
    high20: 4288,
    low20: 3640,
    rsi: 68,
    atrPct: 0.026,
    quality: 7.4,
    ownership: 6.4,
    sentiment: 7.6,
    themes: ["cables", "ai-data-center", "power"],
    thesis: "EHV / specialised cables for industrial and DC power rooms.",
    sector: "Cables",
  },
  {
    symbol: "HAVELLS",
    name: "Havells India",
    last: 1924,
    sma20: 1898,
    sma50: 1864,
    high20: 1998,
    low20: 1788,
    rsi: 58,
    atrPct: 0.019,
    quality: 8.0,
    ownership: 7.2,
    sentiment: 6.7,
    themes: ["power", "ai-data-center"],
    thesis: "Switchgear, cables, cooling — building and DC adjacency.",
    sector: "Electricals",
  },
  {
    symbol: "SIEMENS",
    name: "Siemens",
    last: 3288,
    sma20: 3340,
    sma50: 3412,
    high20: 3520,
    low20: 3188,
    rsi: 44,
    atrPct: 0.021,
    quality: 8.5,
    ownership: 8.1,
    sentiment: 6.0,
    themes: ["power", "ai-data-center", "infra"],
    thesis: "Electrification, drives, and industrial automation for DC campuses.",
    sector: "Capital goods",
  },
  {
    symbol: "ABB",
    name: "ABB India",
    last: 5124,
    sma20: 5210,
    sma50: 5340,
    high20: 5580,
    low20: 4988,
    rsi: 40,
    atrPct: 0.022,
    quality: 8.3,
    ownership: 8.0,
    sentiment: 5.8,
    themes: ["power", "ai-data-center"],
    thesis: "Robotics + electrification kit that data-center builders actually buy.",
    sector: "Capital goods",
  },
  {
    symbol: "CGPOWER",
    name: "CG Power",
    last: 682,
    sma20: 664,
    sma50: 638,
    high20: 718,
    low20: 604,
    rsi: 62,
    atrPct: 0.028,
    quality: 6.8,
    ownership: 6.2,
    sentiment: 7.4,
    themes: ["power", "ai-data-center"],
    thesis: "Motors, transformers, industrial systems — DC power train.",
    sector: "Capital goods",
  },
  {
    symbol: "POWERGRID",
    name: "Power Grid",
    last: 328,
    sma20: 324,
    sma50: 318,
    high20: 342,
    low20: 308,
    rsi: 56,
    atrPct: 0.015,
    quality: 8.1,
    ownership: 7.9,
    sentiment: 6.4,
    themes: ["power", "ai-data-center"],
    thesis: "Grid offtake for hyperscale campuses in India.",
    sector: "Power",
  },
  {
    symbol: "NTPC",
    name: "NTPC",
    last: 412,
    sma20: 406,
    sma50: 398,
    high20: 428,
    low20: 384,
    rsi: 60,
    atrPct: 0.016,
    quality: 7.6,
    ownership: 7.4,
    sentiment: 6.8,
    themes: ["power", "ai-data-center"],
    thesis: "Baseload + renewables; power is the bottleneck for AI compute.",
    sector: "Power",
  },
  {
    symbol: "TATAPOWER",
    name: "Tata Power",
    last: 396,
    sma20: 388,
    sma50: 374,
    high20: 418,
    low20: 352,
    rsi: 64,
    atrPct: 0.023,
    quality: 7.1,
    ownership: 6.8,
    sentiment: 7.2,
    themes: ["power", "ai-data-center"],
    thesis: "Generation + rooftop + potential DC co-location.",
    sector: "Power",
  },
  {
    symbol: "DIXON",
    name: "Dixon Technologies",
    last: 14880,
    sma20: 14240,
    sma50: 13610,
    high20: 15420,
    low20: 12880,
    rsi: 69,
    atrPct: 0.031,
    quality: 7.3,
    ownership: 6.1,
    sentiment: 8.0,
    themes: ["ems", "ai-data-center"],
    thesis: "EMS scale-up; servers and cooling electronics adjacency.",
    sector: "EMS",
  },
  {
    symbol: "KAYNES",
    name: "Kaynes Technology",
    last: 5820,
    sma20: 5640,
    sma50: 5388,
    high20: 6120,
    low20: 4980,
    rsi: 67,
    atrPct: 0.034,
    quality: 6.9,
    ownership: 5.8,
    sentiment: 7.9,
    themes: ["ems", "ai-data-center"],
    thesis: "OSAT / EMS for industrial and compute hardware.",
    sector: "EMS",
  },
  {
    symbol: "SYRMA",
    name: "Syrma SGS",
    last: 512,
    sma20: 498,
    sma50: 474,
    high20: 548,
    low20: 442,
    rsi: 63,
    atrPct: 0.029,
    quality: 6.4,
    ownership: 5.6,
    sentiment: 7.1,
    themes: ["ems", "ai-data-center"],
    thesis: "Electronics manufacturing for industrial and comms gear.",
    sector: "EMS",
  },
  {
    symbol: "THERMAX",
    name: "Thermax",
    last: 3288,
    sma20: 3348,
    sma50: 3410,
    high20: 3588,
    low20: 3120,
    rsi: 43,
    atrPct: 0.022,
    quality: 7.7,
    ownership: 7.2,
    sentiment: 5.9,
    themes: ["power", "ai-data-center"],
    thesis: "Cooling, boilers, energy systems — heat is the other DC bottleneck.",
    sector: "Capital goods",
  },
  {
    symbol: "BHEL",
    name: "BHEL",
    last: 248,
    sma20: 242,
    sma50: 236,
    high20: 268,
    low20: 218,
    rsi: 58,
    atrPct: 0.032,
    quality: 5.8,
    ownership: 6.4,
    sentiment: 6.6,
    themes: ["power"],
    thesis: "Thermal / nuclear equipment; execution risk remains.",
    sector: "Capital goods",
  },
  {
    symbol: "EXIDEIND",
    name: "Exide Industries",
    last: 412,
    sma20: 404,
    sma50: 392,
    high20: 438,
    low20: 368,
    rsi: 61,
    atrPct: 0.021,
    quality: 6.7,
    ownership: 6.3,
    sentiment: 6.5,
    themes: ["power", "auto"],
    thesis: "Storage and backup for industrial power rooms.",
    sector: "Auto ancillary",
  },
  {
    symbol: "BTC",
    name: "Bitcoin",
    last: 97420,
    sma20: 95880,
    sma50: 93210,
    high20: 101400,
    low20: 91200,
    rsi: 58,
    atrPct: 0.028,
    quality: 8.4,
    ownership: 7.0,
    sentiment: 7.2,
    themes: ["crypto", "digital-gold", "delta"],
    thesis: "Base crypto collateral. Size small; weekend gaps are real.",
    sector: "Crypto",
    assetClass: "crypto",
    quote: "USD",
    venue: "Delta",
  },
  {
    symbol: "ETH",
    name: "Ethereum",
    last: 3428,
    sma20: 3360,
    sma50: 3210,
    high20: 3620,
    low20: 3088,
    rsi: 56,
    atrPct: 0.032,
    quality: 7.8,
    ownership: 6.6,
    sentiment: 6.9,
    themes: ["crypto", "delta"],
    thesis: "Smart-contract beta. Follows BTC with extra weekend noise.",
    sector: "Crypto",
    assetClass: "crypto",
    quote: "USD",
    venue: "Delta",
  },
  {
    symbol: "SOL",
    name: "Solana",
    last: 178,
    sma20: 172,
    sma50: 164,
    high20: 196,
    low20: 148,
    rsi: 61,
    atrPct: 0.045,
    quality: 6.4,
    ownership: 5.4,
    sentiment: 7.1,
    themes: ["crypto", "delta"],
    thesis: "High-beta L1. Only if heat and daily-loss gates are clear.",
    sector: "Crypto",
    assetClass: "crypto",
    quote: "USD",
    venue: "Delta",
  },
  {
    symbol: "XRP",
    name: "XRP",
    last: 0.62,
    sma20: 0.6,
    sma50: 0.58,
    high20: 0.68,
    low20: 0.54,
    rsi: 54,
    atrPct: 0.038,
    quality: 6.0,
    ownership: 5.8,
    sentiment: 6.2,
    themes: ["crypto", "delta"],
    thesis: "Payments-rail beta. Event risk around listings and cases.",
    sector: "Crypto",
    assetClass: "crypto",
    quote: "USD",
    venue: "Delta",
  },
  {
    symbol: "USDINR",
    name: "USD / INR",
    last: 83.42,
    sma20: 83.28,
    sma50: 83.05,
    high20: 83.88,
    low20: 82.74,
    rsi: 57,
    atrPct: 0.004,
    quality: 8.0,
    ownership: 8.5,
    sentiment: 6.0,
    themes: ["forex", "rupee", "dollar"],
    thesis: "Rupee pair. Use as a hedge when the equity book is import-heavy.",
    sector: "FX",
    assetClass: "forex",
    quote: "FX",
    venue: "Spot FX",
  },
  {
    symbol: "EURUSD",
    name: "EUR / USD",
    last: 1.0872,
    sma20: 1.084,
    sma50: 1.081,
    high20: 1.096,
    low20: 1.072,
    rsi: 53,
    atrPct: 0.005,
    quality: 7.6,
    ownership: 8.0,
    sentiment: 5.8,
    themes: ["forex", "dollar", "euro"],
    thesis: "G10 dollar proxy. London overlap is the real session.",
    sector: "FX",
    assetClass: "forex",
    quote: "FX",
    venue: "Spot FX",
  },
  {
    symbol: "GBPUSD",
    name: "GBP / USD",
    last: 1.274,
    sma20: 1.271,
    sma50: 1.266,
    high20: 1.289,
    low20: 1.252,
    rsi: 55,
    atrPct: 0.006,
    quality: 7.2,
    ownership: 7.6,
    sentiment: 5.9,
    themes: ["forex", "dollar", "sterling"],
    thesis: "Sterling dollar. Wider than EUR; size down.",
    sector: "FX",
    assetClass: "forex",
    quote: "FX",
    venue: "Spot FX",
  },
  {
    symbol: "USDJPY",
    name: "USD / JPY",
    last: 148.6,
    sma20: 147.8,
    sma50: 146.2,
    high20: 151.4,
    low20: 144.1,
    rsi: 59,
    atrPct: 0.007,
    quality: 7.4,
    ownership: 7.8,
    sentiment: 6.1,
    themes: ["forex", "dollar", "yen"],
    thesis: "Yen funding pair. Watch BoJ surprise risk.",
    sector: "FX",
    assetClass: "forex",
    quote: "FX",
    venue: "Spot FX",
  },
  {
    symbol: "GOLD",
    name: "Gold (MCX)",
    last: 72480,
    sma20: 71840,
    sma50: 70420,
    high20: 73880,
    low20: 68950,
    rsi: 62,
    atrPct: 0.012,
    quality: 8.6,
    ownership: 8.2,
    sentiment: 7.0,
    themes: ["commodity", "gold", "hedge"],
    thesis: "Rupee gold. Hedge sleeve when equity regime is Stress.",
    sector: "Bullion",
    assetClass: "commodity",
    quote: "INR",
    venue: "MCX",
  },
  {
    symbol: "SILVER",
    name: "Silver (MCX)",
    last: 84620,
    sma20: 83210,
    sma50: 81240,
    high20: 87800,
    low20: 78600,
    rsi: 64,
    atrPct: 0.018,
    quality: 7.1,
    ownership: 6.8,
    sentiment: 7.3,
    themes: ["commodity", "silver", "industrial"],
    thesis: "Industrial + monetary metal. Higher beta than gold.",
    sector: "Bullion",
    assetClass: "commodity",
    quote: "INR",
    venue: "MCX",
  },
  {
    symbol: "CRUDE",
    name: "Crude oil (MCX)",
    last: 6840,
    sma20: 6720,
    sma50: 6588,
    high20: 7120,
    low20: 6320,
    rsi: 58,
    atrPct: 0.022,
    quality: 6.6,
    ownership: 6.4,
    sentiment: 6.5,
    themes: ["commodity", "energy", "crude"],
    thesis: "Energy tape. Inverse to a chunk of the equity book.",
    sector: "Energy",
    assetClass: "commodity",
    quote: "INR",
    venue: "MCX",
  },
  {
    symbol: "COPPER",
    name: "Copper (MCX)",
    last: 842,
    sma20: 828,
    sma50: 812,
    high20: 878,
    low20: 786,
    rsi: 60,
    atrPct: 0.016,
    quality: 7.0,
    ownership: 6.6,
    sentiment: 6.8,
    themes: ["commodity", "copper", "ai-data-center"],
    thesis: "Dr. Copper — grid, EVs, and data-center electrical load.",
    sector: "Base metal",
    assetClass: "commodity",
    quote: "INR",
    venue: "MCX",
  },
  {
    symbol: "NATGAS",
    name: "Natural gas (MCX)",
    last: 218,
    sma20: 226,
    sma50: 234,
    high20: 268,
    low20: 198,
    rsi: 42,
    atrPct: 0.035,
    quality: 5.6,
    ownership: 5.2,
    sentiment: 5.4,
    themes: ["commodity", "energy", "gas"],
    thesis: "Whippy energy. Size tiny or skip. Not an order.",
    sector: "Energy",
    assetClass: "commodity",
    quote: "INR",
    venue: "MCX",
  },
];

function withSnap(u: UniverseName): UniverseName {
  const last = SNAPSHOT[u.symbol];
  if (!last) return u;
  const sma20 = u.sma20 || last;
  const sma50 = u.sma50 || last;
  return { ...u, last, sma20, sma50, high20: Math.max(u.high20 || last, last), low20: u.low20 || last * 0.94 };
}

export const UNIVERSE: UniverseName[] = [...CORE_UNIVERSE, ...EXTRA_NAMES, ...SLEEVE_NAMES].map(withSnap);

export function lookup(symbol: string) {
  const u = UNIVERSE.find((x) => x.symbol === symbol.toUpperCase());
  return u ?? null;
}

export function factorParts(u: UniverseName) {
  let tilt = 5;
  tilt += u.sma20 > u.sma50 ? 2 : -2;
  tilt += u.last > u.sma20 ? 1 : -1;
  if (u.rsi < 30) tilt += 1;
  else if (u.rsi > 70) tilt -= 1;
  const technical = Math.min(10, Math.max(0, tilt));
  const span = u.high20 - u.low20;
  const position = span > 0 ? (u.last - u.low20) / span : 0.5;
  const valuation = Math.min(10, Math.max(0, 10 - position * 10));
  return {
    quality: u.quality,
    valuation,
    technical,
    ownership: u.ownership,
    sentiment: u.sentiment,
  } satisfies Record<Factor, number>;
}

export function detectRegime(vix: number, niftyChg: number): Regime {
  if (vix >= 18 || Math.abs(niftyChg) > 0.012) return "Stress";
  if (vix >= 14 || Math.abs(niftyChg) > 0.006) return "Elevated";
  return "Calm";
}

export function assetClassOf(u: UniverseName | null | undefined): AssetClass {
  return u?.assetClass ?? "equity";
}

export function byClass(cls: AssetClass) {
  return UNIVERSE.filter((u) => assetClassOf(u) === cls);
}
