/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AutoRouteImport } from './routes/auto'
import { Route as GreeksRouteImport } from './routes/greeks'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiDeskReadyRouteImport } from './routes/api/desk/ready'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoRoute = AutoRouteImport.update({
  id: '/auto',
  path: '/auto',
  getParentRoute: () => rootRouteImport,
} as any)
const GreeksRoute = GreeksRouteImport.update({
  id: '/greeks',
  path: '/greeks',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeskReadyRoute = ApiDeskReadyRouteImport.update({
  id: '/api/desk/ready',
  path: '/api/desk/ready',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auto': typeof AutoRoute
  '/greeks': typeof GreeksRoute
  '/login': typeof LoginRoute
  '/markets': typeof MarketsRoute
  '/portfolio': typeof PortfolioRoute
  '/research': typeof ResearchRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/desk/ready': typeof ApiDeskReadyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auto': typeof AutoRoute
  '/greeks': typeof GreeksRoute
  '/login': typeof LoginRoute
  '/markets': typeof MarketsRoute
  '/portfolio': typeof PortfolioRoute
  '/research': typeof ResearchRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/desk/ready': typeof ApiDeskReadyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auto': typeof AutoRoute
  '/greeks': typeof GreeksRoute
  '/login': typeof LoginRoute
  '/markets': typeof MarketsRoute
  '/portfolio': typeof PortfolioRoute
  '/research': typeof ResearchRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/desk/ready': typeof ApiDeskReadyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auto'
    | '/greeks'
    | '/login'
    | '/markets'
    | '/portfolio'
    | '/research'
    | '/api/auth/$'
    | '/api/desk/ready'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auto'
    | '/greeks'
    | '/login'
    | '/markets'
    | '/portfolio'
    | '/research'
    | '/api/auth/$'
    | '/api/desk/ready'
  id:
    | '__root__'
    | '/'
    | '/auto'
    | '/greeks'
    | '/login'
    | '/markets'
    | '/portfolio'
    | '/research'
    | '/api/auth/$'
    | '/api/desk/ready'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutoRoute: typeof AutoRoute
  GreeksRoute: typeof GreeksRoute
  LoginRoute: typeof LoginRoute
  MarketsRoute: typeof MarketsRoute
  PortfolioRoute: typeof PortfolioRoute
  ResearchRoute: typeof ResearchRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDeskReadyRoute: typeof ApiDeskReadyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auto': {
      id: '/auto'
      path: '/auto'
      fullPath: '/auto'
      preLoaderRoute: typeof AutoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/greeks': {
      id: '/greeks'
      path: '/greeks'
      fullPath: '/greeks'
      preLoaderRoute: typeof GreeksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/desk/ready': {
      id: '/api/desk/ready'
      path: '/api/desk/ready'
      fullPath: '/api/desk/ready'
      preLoaderRoute: typeof ApiDeskReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutoRoute: AutoRoute,
  GreeksRoute: GreeksRoute,
  LoginRoute: LoginRoute,
  MarketsRoute: MarketsRoute,
  PortfolioRoute: PortfolioRoute,
  ResearchRoute: ResearchRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDeskReadyRoute: ApiDeskReadyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
